import {
  Supernova,
  PulsarContext,
  RemoteVersionIdentifier,
  AnyOutputFile,
  AnyToken,
} from "@supernovaio/sdk-exporters";

import { ExporterConfiguration } from "../config";
import { FileHelper } from "@supernovaio/export-helpers";

import { buildDtcgTree, PlacedToken } from "./build-tree";
import { convertToken } from "./convert";

export const exportConfiguration = Pulsar.exportConfig<ExporterConfiguration>();

Pulsar.export(
  async (
    sdk: Supernova,
    context: PulsarContext,
  ): Promise<Array<AnyOutputFile>> => {
    // Fetch data from design system that is currently being exported (context)
    const remoteVersionIdentifier: RemoteVersionIdentifier = {
      designSystemId: context.dsId,
      versionId: context.versionId,
    };

    // ------------------------------------------------------------
    // Fetch tokens and groups
    // ------------------------------------------------------------

    let tokens = await sdk.tokens.getTokens(remoteVersionIdentifier);
    let tokenGroups = await sdk.tokens.getTokenGroups(remoteVersionIdentifier);

    // ------------------------------------------------------------
    // Apply brand filtering
    // ------------------------------------------------------------

    if (context.brandId) {
      const brands = await sdk.brands.getBrands(remoteVersionIdentifier);

      const brand = brands.find(
        (brand) =>
          brand.id === context.brandId || brand.idInVersion === context.brandId,
      );

      if (!brand) {
        throw new Error(`Unable to find brand ${context.brandId}.`);
      }

      tokens = tokens.filter((token) => token.brandId === brand.id);

      tokenGroups = tokenGroups.filter((group) => group.brandId === brand.id);
    }

    // ------------------------------------------------------------
    // Apply themes
    // ------------------------------------------------------------

    if (context.themeIds && context.themeIds.length > 0) {
      const themes = await sdk.tokens.getTokenThemes(remoteVersionIdentifier);

      const themesToApply = context.themeIds.map((themeId) => {
        const theme = themes.find(
          (theme) => theme.id === themeId || theme.idInVersion === themeId,
        );

        if (!theme) {
          throw new Error(`Unable to find theme ${themeId}.`);
        }

        return theme;
      });

      tokens = sdk.tokens.computeTokensByApplyingThemes(
        tokens,
        tokens,
        themesToApply,
      );
    }

    // ------------------------------------------------------------
    // Convert Supernova tokens into DTCG tokens
    // ------------------------------------------------------------

    const placedTokens: PlacedToken[] = [];
    const warnings: string[] = [];

    for (const token of tokens) {
      const typedToken = token as AnyToken;

      const converted = convertToken(
        typedToken.tokenType,
        typedToken.name,
        typedToken.description,
        typedToken.value,
        exportConfiguration,
      );

      warnings.push(...converted.warnings);

      if (!converted.token) {
        continue;
      }

      placedTokens.push({
        path: typedToken.tokenPath ?? [typedToken.name],
        token: converted.token,
      });
    }

    // ------------------------------------------------------------
    // Build DTCG document
    // ------------------------------------------------------------

    const document = buildDtcgTree(placedTokens);

    let content = JSON.stringify(document, null, 2);

    // ------------------------------------------------------------
    // Optional disclaimer
    // ------------------------------------------------------------

    if (exportConfiguration.showGeneratedFileDisclaimer) {
      content =
        `/* This file was generated by Supernova, don't change by hand */\n` +
        content;
    }

    // ------------------------------------------------------------
    // Output
    // ------------------------------------------------------------

    return [
      FileHelper.createTextFile({
        relativePath: "./",
        fileName: "tokens.json",
        content,
      }),
    ];
  },
);
